### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by rohit-vijayakumar** [anranknight/EEG-Transformer#1]
Would it be possible to share the pre-trained weights of the transformer, I would like to transfer learn the transformer to a BCI task

**Comment by eeyhsong** [comment]
Hello, this work wasn't using pre-training, and also not the same as the original Transformer or ViT. And, I suggest to pre-train with subject-independent data of your task and then fine-tune on the subject-specific data.

**Comment by 110lmy** [comment]
May I ask, according to the matrix obtained after space conversion, how to view the correlation between each electrode? That is to say, when you think about a certain kind of movement, which electrodes play the most important role, which electrodes are useless or have little influence, and what is the correlation between each electrode?

**Comment by eeyhsong** [comment]
Hello, @110lmy  
You mean the CSP part or spatial attention? You can use a heatmap to illustrate the covariance matrix or the attention map. 
In general, motor cortex of parietal lobe is relevant to motor imagery, such as C3, Cz, and C4.
In my view, there is not yet sufficient evidence to explain the correlation between each electrode for different tasks. But we know the correlation of the close channels will be higher.

**Comment by 110lmy** [comment]
Thank you very much for your answer！ I would like to ask why the number of convolution kernels in the position coding of the time conversion part is 2? And the convolution kernel for the compressed part why is it 10?
