### ISSUE TITLE
How to apply it to a 2-class task? 

### ISSUE THREAD

**Issue by supnov** [anranknight/EEG-Transformer#2]
It's an excellent work that inspired me a lot. Now I am appling it to a 2-class task for DatasetIV-2b. Which parameter should I change? 
I've found some potential code, Could you help to locate the para that needs modifing? Thank you!
In Trans.py:
  Line 130: **forward_expansion=4**
  Line 167: emb_size=10, depth=3, **n_classes=4**
  LIne 253: **self.c_dim=4**
In common_spatial_pattern.py:
  Line 15: idx_3=... (comment this line?)
  Line 18: in **range(4)** and following elif for n_class==3
  Line 70: Wb = np.concatenate((**W[0][:, 0:4], W[1][:, 0:4], W[2][:, 0:4], W[3][:, 0:4])**, axis=1)
 Thanks again.

**Comment by LUCYJON** [comment]
I found that the accuracy is below 50% after I run this code without any change in.
Is any parameters wrong?
Thanks!

**Comment by 384068026** [comment]
> 我运行这段代码后发现准确率低于 50%，没有任何变化。 是否有任何参数错误？ 谢谢！

我运行了代码之后，在2a数据集上准确率大概在79%，无法达到论文里的82%，感觉可能是参数存在问题……但是不知道是哪里需要调参，希望能得到作者提供的论文结果对应的参数。非常感谢！

**Comment by 384068026** [comment]
> 我运行这段代码后发现准确率低于 50%，没有任何变化。 是否有任何参数错误？ 谢谢！

我运行了代码之后，在2a数据集上准确率大概在79%，无法达到论文里的82%，感觉可能是参数存在问题……但是不知道是哪里需要调参，希望能得到作者提供的论文结果对应的参数。非常感谢！

**Comment by XJWang0** [comment]
> > 我运行这段代码后发现准确率低于 50%，没有任何变化。 是否有任何参数错误？ 谢谢！
> 
> 我运行了代码之后，在2a数据集上准确率大概在79%，无法达到论文里的82%，感觉可能是参数存在问题……但是不知道是哪里需要调参，希望能得到作者提供的论文结果对应的参数。非常感谢！

我用matlab运行getData.m文件时，显示报错“无法识别函数或变量‘sload’”，请问该怎么解决？谢谢！

**Comment by 384068026** [comment]
> > > 我运行代码后发现准确率达到 50%，没有任何变化。是否有任何参数错误？
> > 
> > 
> > 我运行了代码之后，在 2 月的数据集上准确率大概在 79%，无法达到论文里的 82%，可能存在参数……但是不知道需要调参，希望能得到作者的论文结果的参数。非常感谢！
> 
> 我用matlab运行getData.m文件时，显示报错“无法识别函数或'sload'”，请问如何解决？谢谢！

留一下你的联系方式，可以讨论一下

**Comment by XJWang0** [comment]
> 

微信号：WXJ_1010_10

**Comment by XJWang0** [comment]
> > > > 我运行代码后发现准确率达到 50%，没有任何变化。是否有任何参数错误？
> > > 
> > > 
> > > 我运行了代码之后，在 2 月的数据集上准确率大概在 79%，无法达到论文里的 82%，可能存在参数……但是不知道需要调参，希望能得到作者的论文结果的参数。非常感谢！
> > 
> > 
> > 我用matlab运行getData.m文件时，显示报错“无法识别函数或'sload'”，请问如何解决？谢谢！
> 
> 留一下你的联系方式，可以讨论一下

微信号：WXJ_1010_10

**Comment by pskadasi** [comment]
@eeyhsong: hi, what changes are to be made for 10 class classification in [common_spatial_pattern.py](https://github.com/eeyhsong/EEG-Transformer/blob/main/common_spatial_pattern.py) file. please let me know. Thanks

**Comment by pskadasi** [comment]
I am able to run the code now. Thanks
