### ISSUE TITLE
代码运行后accuracy不能达到论文所诉82%

### ISSUE THREAD

**Issue by 384068026** [anranknight/EEG-Transformer#3]
作者您好，非常感谢您发表的这篇论文，在拜读了您的文章后对我产生了非常大的启发。
但是我在复现您的文章时，始终不能达到论文所诉的2a数据集上的82%的accuracy，我这边感觉可能是调参的问题，希望能得到您技术上的帮助。非常感谢！

**Comment by eeyhsong** [comment]
您好，建议先确认下数据预处理过程是否一致。参数设定的话，slice size影响大一些，此外transformer的常用参数也会有影响，可以尝试下
