### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by sadaf92** [anranknight/EEG-Transformer#4]
Hi there,
I'm trying to implement your code on the BCI IV 2a dataset. However, I'm wondering how is the structure of the label and data in your mat file since I couldn't rebuild the mat file based on the "getData.m" function. If you can provide a tree structure of the data regarding trials and labels, it will be clearer.

**Comment by 384068026** [comment]
I am not sure if I can help you, but I have finished the code reproduction, if you need data, you can contact me, my email is shichi1999js@163.com

**Comment by 384068026** [comment]
I'm not sure if I can help you, but I've finished implementing the code. If you need data, you can contact me. My email is shichi1999js@163.com

**Comment by sadaf92** [comment]
Thank you so much for your response. I already loaded the data. What I faced is that the results I achieved are different from what is mentioned in the paper. I'm wondering if there is anything that I should change regarding the data. I used the default version of the code which was without standardization. Could it be the reason? Or whatever else do you guess that are helpful to implement?

**Comment by 384068026** [comment]
I have a similar problem with you at work. I found that the data of a single test object under different initialization conditions had a significant impact on the final result. That is, data from the same object in different initial seeds can produce huge differences in results (about 3%-10%). The overall accuracy is similar to that of the paper, but there is a certain gap (about 1%-2%). I am also making some changes at the moment, hoping to improve.

**Comment by 384068026** [comment]
I have a similar problem with you at work. I found that the data of a single test object under different initialization conditions had a significant impact on the final result. That is, the data of the same object in different initial seeds will produce a huge difference in results (about 3%-10%) and I feel that it may be trapped in a local optimal solution, but I am not sure because I am a novice and have limited ability. Although the mean value of the results is relatively stable, the variance is relatively large. The overall accuracy is similar to that of the paper, but there is a certain gap (about 1%-2%). I am also making some changes at the moment, hoping to improve.

**Comment by eeyhsong** [comment]
Hello, please make sure the preprocessing is okay firstly.  The choice of the slice size has some impact. Then you may try to adjust common parameters of Transformer.

**Comment by pskadasi** [comment]
HI @eeyhsong, can you help me with the dataset format, how should I give input to the code?

I have .mat file which has dimensions 62x47001x15
62 channels, 47001 time points, 15 subjects

**Comment by eeyhsong** [comment]
The input shape of the model [Trans]  is (batch, 1, channels, samples), you can resize in function [get_source_data()]. 
And for your dateset, you need to segement the whole data into trials using the markers.

**Comment by eeyhsong** [comment]
The input shape of the model [Trans] is (batch, 1, channels, samples), you can resize in function [get_source_data()].
And for your dataset, you need to segment the whole data into trials using the markers.

**Comment by eeyhsong** [comment]
@pskadasi hi, 
The input shape of the model [Trans] is (batch, 1, channels, samples), you can resize in function [get_source_data()].
And for your dataset, you need to segment the whole data into trials using the markers.

**Comment by 110lmy** [comment]
> HI @eeyhsong, can you help me with the dataset format, how should I give input to the code?
> 
> I have .mat file which has dimensions 62x47001x15 62 channels, 47001 time points, 15 subjects
Hello, could you please share your data set with me? Thanks a million!! My email is lmy232496@163.com

**Comment by eeyhsong** [comment]
@110lmy 我不理解，您都不愿意点个赞，还要问代码并让我帮您处理数据并发到邮箱❓

**Comment by pskadasi** [comment]
hi did you get the dataset?, if not let me know again. will send it

**Comment by Kaverigg** [comment]
@pskadasi Can you please send me the dataset link because i'm unable to convert to .mat file for training from .gdf file.

**Comment by pskadasi** [comment]
hi @Kaverigg how should i send the dataset?

**Comment by Kaverigg** [comment]
> hi @Kaverigg how should i send the dataset?

send me the drive link to download via kaverialphaics@gmail.com

**Comment by 110lmy** [comment]
链接：https://pan.baidu.com/s/1vlNjAV0ZWTdS7x0xvHHJdg
提取码：2l3t
这时数据集的百度网盘


| |
刘梦园
|
|
***@***.***
|
---- Replied Message ----
| From | Kaveri ***@***.***> |
| Date | 5/17/2024 23:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [eeyhsong/EEG-Transformer] About dataset (Issue #4) |

hi @Kaverigg how should i send the dataset?

send me the drive link to download via ***@***.***

**Comment by Kaverigg** [comment]
> 链接：https://pan.baidu.com/s/1vlNjAV0ZWTdS7x0xvHHJdg 提取码：2l3t 这时数据集的百度网盘 | | 刘梦园 | | ***@***.*** | ---- Replied Message ---- | From | Kaveri ***@***.***> | | Date | 5/17/2024 23:43 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [eeyhsong/EEG-Transformer] About dataset (Issue #4) | hi @Kaverigg how should i send the dataset? send me the drive link to download via ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

send me Hi msg to above mentioned mail id. Thank you

**Comment by Kaverigg** [comment]
> I'm not sure if I can help you, but I've finished implementing the code. If you need data, you can contact me. My email is [shichi1999js@163.com](mailto:shichi1999js@163.com)
Thank you so much for sharing data.
