### ISSUE TITLE
How do I understand slicing

### ISSUE THREAD

**Issue by ll643989** [anranknight/EEG-Transformer#5]
The slice size is 10? How should I understand the slicing of the data

**Comment by eeyhsong** [comment]
hello, it's just like splitting patches in ViT. Slicing is spliting in the time dimension.

**Comment by 110lmy** [comment]
Could you please add the code comments and what needs to be modified?

**Comment by eeyhsong** [comment]
You need to adjust the data input and result output, such as path, data size, etc.

**Comment by 110lmy** [comment]
Which version of pytorch are you using
