### ISSUE TITLE
Could you please share the random seed for training and label for BCI data E file?

### ISSUE THREAD

**Issue by zewailaa** [anranknight/EEG-Transformer#6]
thank you very much

**Comment by 110lmy** [comment]
Excuse me, how does the part of location code work? Do I take sines and cosines?

**Comment by eeyhsong** [comment]
@zewailaa hello, you may see the randomly generated seed in the main function at the end of the code.

**Comment by eeyhsong** [comment]
@110lmy You mean position embedding? We don't use this design in the code.

**Comment by 110lmy** [comment]
It's not positional embedding, it's positional coding. Wasn't position coding used before compression slices in the time conversion section?

**Comment by eeyhsong** [comment]
@110lmy Sorry for the misunderstanding. In my provious experiments, the position embedding strategies as used in images performed not well for EEG signals. So I chose to use one convolutional layer to capture the position information.

**Comment by 110lmy** [comment]
卷积层获取位置信息是怎么获取的？我还想问一下，为什么在空间变换使用单头注意力，但是在时间变换使用多头注意力？谢谢回复


| |
刘梦园
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/7/2022 11:32 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [eeyhsong/EEG-Transformer] Could you please share the random seed for training and label for BCI data E file? (Issue #6) |

@110lmy Sorry for the misunderstanding. In my provious experiments, the position embedding strategies as used in images performed not well for EEG signals. So I chose to use one convolutional layer to capture the position information.

**Comment by eeyhsong** [comment]
@110lmy hi, lmy
- In my view, position information in EEG is still a kind of local correlation, which can be encapsulated by convolution.
- You could also use multi-head in channel attention. That is a performance enhancing strategy, but the interpretability for EEG needs to be further explored. 
- Besides, I found too long data is not easy to caluculate the attention weight well. 
- At last, please wait for the next version.
