### ISSUE TITLE
关于数据划分的一个疑问

### ISSUE THREAD

**Issue by h1deOnBush** [anranknight/EEG-Transformer#7]
代码中是将所有576个trial合起来然后选516个用于训练。
如果改为按照A01_T用于训练，A01E用于测试这样的数据划分的话，即288个trial用于训练,288个trial用于测试，模型的结果看上去不是很理想。
请问大佬针对这种情况有什么可以优化的手段吗

**Comment by eeyhsong** [comment]
- Glad to see you noticed the key point! I commented in the code that the data division is not for regious academic paper.
- This version is a pilot study to apply Transformer in EEG signals. So, the design of the feature extraction part is conservative to reflect the performance of the pure self-attention. Then...you know?
- Another choise is to use tricks to mitigate overfitting, such as regular, early stop, pooling, etc.
- If don't, please waiting for the latest version, which will be released soon.

**Comment by h1deOnBush** [comment]
appreciate that and looking foward to it
