### ISSUE TITLE
Dataset labelling issue

### ISSUE THREAD

**Issue by MerlinK75** [anranknight/EEG-Transformer#8]
Hello
I have been trying to get your getData.m function working but I have run into an issue with labelling the evaluation datasets. Each time I run the code, the labels for all of the subject's evaluation data are labelled as NaN, preventing the Trans.py code to have a test accuracy score other than 0.

I looked at the BCI competition IV website and subject 1 from dataset 2a should have class labels but when I run 
[s, HDR] = sload('dir of A01E');
The HDR.ClassLabels are all NaN so am unsure where I am going wrong.
Any help would be appreciated.
Best
Merlin

**Comment by eeyhsong** [comment]
@MerlinK75 Hello Merlin,
The original dataset files don't have the results for evaluation. Try here https://www.bbci.de/competition/iv/results/#dataset2a
Sincerely,
Yonghao

**Comment by MerlinK75** [comment]
Hello Yonghao 
My issue has been solved, thank you for helping me and for the quick reply.
Best
Merlin

**Comment by pskadasi** [comment]
Hi, what is the reason, the same data is used for both train and test? this is leading to good performance. But this shouldn't be the case right? Please enlighten me if I am missing something

**Comment by MerlinK75** [comment]
I used A0#E and A0#T for the test and train data respectively. The A0#E data wasn't labelled and I was confused why that was the case, not realising that the test data was downloaded from a different part of the BCI website. I didn't use the same data as test and train as I thought the competition's purpose was to have two other datasets for the test and train inputs but have them as the same individual. I hope this helped.

**Comment by pskadasi** [comment]
Thanks
