### ISSUE TITLE
Dataset 2a accuracy surprisingly lower than the studies results

### ISSUE THREAD

**Issue by MerlinK75** [anranknight/EEG-Transformer#9]
Hello 
After running the transformer a couple of times, I'm receiving significantly smaller results compared to the study's results. I've attached an image of one of my confusion matrices which in comparison with the study, is much worse.
![image](https://user-images.githubusercontent.com/117939938/203300406-a0986731-91fc-47bc-b385-d0a5bfe16bed.png)
The only code I've edited was for the purpose of using it in google collaborate, otherwise, all the code is the same as how it was here on GitHub. What would be the cause of this and am I missing something quite obvious that is missing?
Best
Merlin

**Comment by eeyhsong** [comment]
The results in the paper used cross-validation. But the latest code uses T session for training and E session for test. You could wait for the next version, which may be released recently.

**Comment by MerlinK75** [comment]
Ok, thank you for the clarification
